import pandas as pd
import os

def main():
    csv_file = "output/rmsd_scores.csv"
    output_file = "output/chimerax_scripts/evolution_of_destruction.cxc"
    
    if not os.path.exists(csv_file):
        print("RMSD file not found.")
        return
        
    # 1. Load Data
    df = pd.read_csv(csv_file)
    
    # 2. Sort by RMSD ASCENDING (Low -> High)
    # User wants "Evolution to the Highest", so start small.
    df = df.sort_values(by="RMSD (Angstroms)", ascending=True)
    
    # 3. Start building the script
    script = []
    script.append("# Evolution of Destruction: From Stable to Broken")
    script.append("# Generated by Antigravity")
    script.append("close session")
    script.append("log text \"Starting Evolution...\"")
    
    # Open Wild Type (Always #1)
    script.append(f"open ../../data/structures/tp53_wt.cif")
    script.append("color #1 blue")
    script.append("style #1 stick")
    script.append("2dlabels create title text \"Baseline: Wild Type P53\" xpos 0.5 ypos 0.9 size 30 color white")
    script.append("wait 60")
    
    # 4. Loop through mutations
    rank = 1
    total = len(df)
    
    for _, row in df.iterrows():
        mutation = row['Mutation'] # R213Q
        rmsd = row['RMSD (Angstroms)']
        gene = row['gene'] if 'gene' in row else "TP53" 
        
        filename = f"{gene.lower()}_{mutation.lower()}.cif"
        filepath = f"../../data/structures/{filename}"
        
        script.append(f"\n# Step {rank}/{total}: {mutation}")
        # Update the title label text
        script.append(f"2dlabels change title text \"Rank {rank}: {mutation} (Damage: {rmsd} A)\"")
        
        # Open Mutant as #3 (Because #2 is now the Labels)
        script.append(f"open {filepath}")
        
        # Align (Mutant #3 to Wild Type #1)
        script.append("matchmaker #3 to #1")
        
        # Style
        script.append("color #3 red")
        script.append("style #3 stick")
        
        # Highlight Sphere
        color = "yellow"
        if rmsd < 15: color = "green"
        elif rmsd > 30: color = "red"
        
        # Get residue number from mutation code (e.g. R213Q -> 213)
        res_num = "".join(filter(str.isdigit, mutation))
        
        script.append(f"show #{3}:{res_num} atoms")
        script.append(f"style #{3}:{res_num} sphere")
        script.append(f"color #{3}:{res_num} {color}")

        script.append("view orient") 
        
        # Wait to let user see it
        script.append("wait 120") # 2 seconds @ 60fps
        
        # Cleanup for next step (unless it's the last one)
        if rank < total:
            script.append("close #3")
            
        rank += 1
        
    script.append("2dlabels change title text \"EVOLUTION COMPLETE: MAX DAMAGE REACHED\" color red")

    # Write to file
    with open(output_file, 'w') as f:
        f.write("\n".join(script))
        
    print(f"Created movie script: {output_file}")

if __name__ == "__main__":
    main()
